 <br />
 <table width="100%" border="0" id="listTbl">
  <tr>
    <td align="center" width="16%"><strong><a title="Buy Flying Eagle Cents" class="brownLink" href="http://www.allsmallcents.com/Flying-Eagle-Penny.php"><img src="http://www.allsmallcents.com/img/Flying_Eagle.jpg" alt="Flying Eagle Cent" width="50" height="50" align="middle" /></a> <a title="Buy Flying Eagle pennies" class="brownLink" href="http://www.allsmallcents.com/Flying-Eagle-Penny.php">Flying Eagle</a></strong></td>
    <td align="center" width="16%"><strong><a title="Buy Indian Head Cents" class="brownLink" href="http://www.allsmallcents.com/Indian-Head-Penny.php"><img src="http://www.allsmallcents.com/img/Indian_Head.jpg" alt="Indian Head Pennies" width="50" height="50" align="middle" /></a> <a title="Buy Indian Head Cents" class="brownLink" href="http://www.allsmallcents.com/Indian-Head-Penny.php">Indian Head</a></strong></td>
    <td align="center" width="16%"><strong><a title="Buy Lincoln Wheat Coins, Sets and Rolls" class="brownLink" href="http://www.allsmallcents.com/Lincoln-Wheat-Penny.php"><img src="http://www.allsmallcents.com/img/Lincoln_Wheat.jpg" alt="Buy Lincoln Wheat Pennies, Sets and Rolls" width="50" height="50" align="middle" /></a> <a title="Buy Lincoln Wheat Coins, Sets and Rolls" class="brownLink" href="http://www.allsmallcents.com/Lincoln-Wheat-Penny.php">Wheat</a></strong></td>
    <td align="center" width="16%"><strong><a class="brownLink" href="http://www.allsmallcents.com/Lincoln-Memorial-Penny.php"><img src="http://www.allsmallcents.com/img/Lincoln_Memorial.jpg" alt="Buy Lincoln Memorial Coins, Sets and Rolls" width="50" height="50" align="middle" /></a> <a title="Buy Lincoln Memorial Pennies, Sets and Rolls" class="brownLink" href="http://www.allsmallcents.com/Lincoln-Memorial-Penny.php">Memorial</a></strong></td>
    <td align="center" width="16%"><strong><a title="Buy Lincoln Bicentennial Pennies, Sets and Rolls" class="brownLink" href="http://www.allsmallcents.com/Lincoln-Bicentennial-Penny.php"><img src="http://www.allsmallcents.com/img/Lincoln_Bicentennial.jpg" alt="Buy Lincoln Bicentennial Coins, Sets and Rolls" width="50" height="50" align="middle" /></a> <a title="Buy Lincoln Bicentennial Coins, Sets and Rolls" class="brownLink" href="http://www.allsmallcents.com/Lincoln-Bicentennial-Penny.php">Bicentennial</a></strong></td>
    <td align="center" width="16%"><strong><a title="Buy Union Shield Pennies, Sets and Rolls" class="brownLink" href="http://www.allsmallcents.com/Union-Shield-Penny.php"><img src="http://www.allsmallcents.com/img/Union_Shield.jpg" alt="Buy Union Shield Coins, Sets and Rolls" width="50" height="50" align="middle" /></a> <a title="Buy Union Shield Coins, Sets and Rolls" class="brownLink" href="http://www.allsmallcents.com/Union-Shield-Penny.php">Shield</a></strong></td>    
  </tr>
</table>